DATA:
  batch_size: 1024
  cifar_root_dir: /home/min9813/project/data/cifar-10-batches-py
  cifar_meta_file: batches.meta
  cifar_train_reg_exp: data_batch*[1|2|3|4]
  cifar_val_reg_exp: data_batch_5
  cifar_test_reg_exp: test_batch

  feature_root_dir: /home/min9813/project/data/cifar_feature/

TRAIN:
  total_epoch: 500
  start_epoch: 1
  fp16: False
  self_supervised_method: simclr
  color_aug: True
  shape_aug: True

OPTIM:
  optimizer: adam
  lr: 0.001
  lr_scheduler: "patience"
  lr_gamma: 0.1
  lr_cooldown: 5
  lr_patience: 20
  lr_min: 0.000001


LOG:
  save_dir: ../logs
  train_print_iter: 10000

MODEL:
  save_dir: ../models
  resume_net_path: ""  
  resume_opt_path: ""
  resume: False
  network: resnet18
  # head: [512,256]
  linear_layers: [256]
  delete_old: True

debug: False
run_mode: train
seed: 1234
gpus: "0"
use_multi_gpu: False
cuda_id: 0
num_workers: 4
input_ch: 3
num_classes: 128